### ISSUE TITLE
Not working for Magento 2.4

### ISSUE THREAD

**Issue by indunie** [Dan0sz/RedirectSimpleProducts#3]
Hi,
You have done a great Job. Thanks for the plugin.

I just tried to install this on Magento 2.4 and it seems not working.
Could you please let me know which modifications do I need to do to work this.

Thanks

Regards,
Indunie

**Comment by Dan0sz** [comment]
Oof! Sorry. I haven't been able to support my (free) Magento 2 modules anymore, since I'm not working with M2 anymore.

I suggest forking it, and fix it yourself, or check out some of the other forks?
